name: nodeactions

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  test:
    name: testing node
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version:  ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Test
      run: npm test
        
